# ------ Deployment ------

services:
  # Client service
  frontend:
    image: shreelaxmihegde/accommate-frontend:latest
    ports:
      - "80:80"
    networks:
      - app_network

    depends_on:
      - backend

  # Server service
  backend:
    image: shreelaxmihegde/accommate-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app_network

    environment:
      - ATLASDB_URL: ${{ ATLASDB_URL }}

# Network
networks:
  app_network:
    driver: bridge